kind: Namespace
apiVersion: v1
metadata:
  name: csi-lvm-system

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: direct-storage
provisioner: lvm.csi.justinsb.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

---

# All of the individual sidecar RBAC roles get bound
# to this account.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-lvmplugin
  namespace: csi-lvm-system
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: attacher-cluster-role
  name: csi-lvmplugin-attacher-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-attacher-runner
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
  namespace: csi-lvm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: health-monitor-controller-cluster-role
  name: csi-lvmplugin-health-monitor-controller-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-health-monitor-controller-runner
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
  namespace: csi-lvm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: provisioner-cluster-role
  name: csi-lvmplugin-provisioner-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-provisioner-runner
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
  namespace: csi-lvm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: resizer-cluster-role
  name: csi-lvmplugin-resizer-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-resizer-runner
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
  namespace: csi-lvm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: snapshotter-cluster-role
  name: csi-lvmplugin-snapshotter-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-snapshotter-runner
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
  namespace: csi-lvm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: attacher-role
  name: csi-lvmplugin-attacher-role
  namespace: csi-lvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-attacher-cfg
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: health-monitor-controller-role
  name: csi-lvmplugin-health-monitor-controller-role
  namespace: csi-lvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-health-monitor-controller-cfg
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: provisioner-role
  name: csi-lvmplugin-provisioner-role
  namespace: csi-lvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-provisioner-cfg
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: resizer-role
  name: csi-lvmplugin-resizer-role
  namespace: csi-lvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-resizer-cfg
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: snapshotter-role
  name: csi-lvmplugin-snapshotter-role
  namespace: csi-lvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-snapshotter-leaderelection
subjects:
- kind: ServiceAccount
  name: csi-lvmplugin
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: csi-lvm-system
  name: csi-lvmplugin
  labels:
    app.kubernetes.io/instance: lvm.csi.justinsb.com
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-lvmplugin
    app.kubernetes.io/component: plugin
spec:
  serviceName: "csi-lvmplugin"
  # One replica only:
  # Host path driver only works when everything runs
  # on a single node.
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: lvm.csi.justinsb.com
      app.kubernetes.io/part-of: csi-driver-host-path
      app.kubernetes.io/name: csi-lvmplugin
      app.kubernetes.io/component: plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: lvm.csi.justinsb.com
        app.kubernetes.io/part-of: csi-driver-host-path
        app.kubernetes.io/name: csi-lvmplugin
        app.kubernetes.io/component: plugin
    spec:
      serviceAccountName: csi-lvmplugin
      containers:
        - name: lvmplugin
          image: justinsb/csi-lvm-controller:latest
          args:
            - "--drivername=lvm.csi.justinsb.com"
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          ports:
          - containerPort: 9898
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
              name: plugins-dir
            - mountPath: /csi-data-dir
              name: csi-data-dir
            - mountPath: /dev
              name: dev-dir

        - name: csi-external-health-monitor-controller
          image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.6.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.lvm.justinsb.com/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          - mountPath: /registration
            name: registration-dir
          - mountPath: /csi-data-dir
            name: csi-data-dir

        - name: liveness-probe
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          image: registry.k8s.io/sig-storage/livenessprobe:v2.7.0
          args:
          - --csi-address=/csi/csi.sock
          - --health-port=9898

        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v3.5.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.2.1
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir

        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.5.0
          args:
            - -v=5
            - -csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir

        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.0.1
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.lvm.justinsb.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
          name: plugins-dir
        - hostPath:
            # 'path' is where PV data is persisted on host.
            # using /tmp is also possible while the PVs will not available after plugin container recreation or host reboot
            path: /var/lib/csi-lvm-data/
            type: DirectoryOrCreate
          name: csi-data-dir
        - hostPath:
            path: /dev
            type: Directory
          name: dev-dir
