apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-csi-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: direct-storage

---

kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
  namespace: default
spec:
  containers:
    - name: my-frontend
      image: "busybox:latest"
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: my-csi-volume
